apiVersion: v1
kind: Service
metadata:
  name: metacognition
  namespace: endogenai-modules
spec:
  selector:
    app: metacognition
  ports:
  - name: a2a
    port: 8231
    targetPort: 8231
  - name: mcp
    port: 8331
    targetPort: 8331
