apiVersion: v1
kind: Service
metadata:
  name: affective
  namespace: endogenai-modules
spec:
  selector:
    app: affective
  ports:
  - name: a2a
    port: 8215
    targetPort: 8215
  - name: mcp
    port: 8315
    targetPort: 8315
