apiVersion: v1
kind: Service
metadata:
  name: long-term-memory
  namespace: endogenai-modules
spec:
  selector:
    app: long-term-memory
  ports:
  - name: a2a
    port: 8212
    targetPort: 8212
  - name: mcp
    port: 8312
    targetPort: 8312
